---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: _includes
  label: Includes
  create: all
  match: "**/*"
  new_doc_ext: liquid
- type: directory
  path: _data
  label: Data
  create: documents
  match: "**/*"
  new_doc_ext: app
- type: directory
  path: blog
  label: Blog
  create: all
  match: "**/*"
  new_doc_ext: md
upload_dir: ''
public_path: https://res.cloudinary.com/dypy0397h/image/upload
front_matter_path: https://res.cloudinary.com/dypy0397h/image/upload
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_output_directory: _site
  install_dependencies_command: npx install @11ty/eleventy
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: "@11ty/eleventy"
